name: Darwin
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustc --version
      - run: rustup target add wasm32-unknown-unknown
      - uses: denoland/setup-deno@v1
      - run: make build
      - run: make nbuild
