name: hash
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: rustc --version
      - run: rustup install nightly
      - run: rustup default 1.84.0
      - run: rustup target add wasm32-unknown-unknown
      - run: rustup target add wasm32-unknown-unknown --toolchain nightly
      - uses: denoland/setup-deno@v1
      - run: make build
      #- run: make nbuild
      - run: ls
        working-directory: ./output
      - run: |
          cp Cargo.lock ./output/Cargo.${{runner.os}}.lock
      - run: cargo tree --target wasm32-unknown-unknown > ./output/tree.${{runner.os}}.txt
      - uses: actions/upload-artifact@master
        with:
          name: all-artifacts-${{runner.os}}
          path: output/
